# Generated by Django 3.1.6 on 2021-04-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardware',
            old_name='kid_id',
            new_name='kit_id',
        ),
    ]
