# Generated by Django 3.1.6 on 2021-04-30 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210430_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='hardware_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tracker.hardware'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='software_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tracker.software'),
        ),
    ]
