# Generated by Django 3.1.6 on 2021-04-30 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20210430_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumable',
            old_name='date_purchased',
            new_name='date_refilled',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='hardware_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tracker.hardware'),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='month_interval',
            field=models.IntegerField(default=0),
        ),
    ]
