# Generated by Django 3.1.6 on 2021-05-10 20:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0005_auto_20210430_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_assigned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='date_refilled',
            field=models.DateField(default=datetime.date(2021, 5, 10)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='origin',
            field=models.DateField(default=datetime.date(2021, 5, 10)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_origin',
            field=models.DateField(default=datetime.date(2021, 5, 10)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_purchased',
            field=models.DateField(default=datetime.date(2021, 5, 10)),
        ),
        migrations.AlterField(
            model_name='software',
            name='date_installed',
            field=models.DateField(default=datetime.date(2021, 5, 10)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tracker.address'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 5, 10)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='date_issued',
            field=models.DateField(default=datetime.date(2021, 5, 10)),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='date_purchased',
            field=models.DateField(default=datetime.date(2021, 5, 10)),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2021, 5, 10)),
        ),
    ]
